# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/art/Supercharged-Juggernaut-Wasps

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/art/Supercharged-Juggernaut-Wasps

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/art/Supercharged-Juggernaut-Wasps/CMakeFiles /home/art/Supercharged-Juggernaut-Wasps/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/art/Supercharged-Juggernaut-Wasps/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Supercharged-Juggernaut-Wasps

# Build rule for target.
Supercharged-Juggernaut-Wasps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Supercharged-Juggernaut-Wasps
.PHONY : Supercharged-Juggernaut-Wasps

# fast build rule for target.
Supercharged-Juggernaut-Wasps/fast:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build
.PHONY : Supercharged-Juggernaut-Wasps/fast

source/Bullet.o: source/Bullet.cpp.o

.PHONY : source/Bullet.o

# target to build an object file
source/Bullet.cpp.o:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/Bullet.cpp.o
.PHONY : source/Bullet.cpp.o

source/Bullet.i: source/Bullet.cpp.i

.PHONY : source/Bullet.i

# target to preprocess a source file
source/Bullet.cpp.i:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/Bullet.cpp.i
.PHONY : source/Bullet.cpp.i

source/Bullet.s: source/Bullet.cpp.s

.PHONY : source/Bullet.s

# target to generate assembly for a file
source/Bullet.cpp.s:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/Bullet.cpp.s
.PHONY : source/Bullet.cpp.s

source/Display.o: source/Display.cpp.o

.PHONY : source/Display.o

# target to build an object file
source/Display.cpp.o:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/Display.cpp.o
.PHONY : source/Display.cpp.o

source/Display.i: source/Display.cpp.i

.PHONY : source/Display.i

# target to preprocess a source file
source/Display.cpp.i:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/Display.cpp.i
.PHONY : source/Display.cpp.i

source/Display.s: source/Display.cpp.s

.PHONY : source/Display.s

# target to generate assembly for a file
source/Display.cpp.s:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/Display.cpp.s
.PHONY : source/Display.cpp.s

source/GameState.o: source/GameState.cpp.o

.PHONY : source/GameState.o

# target to build an object file
source/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/GameState.cpp.o
.PHONY : source/GameState.cpp.o

source/GameState.i: source/GameState.cpp.i

.PHONY : source/GameState.i

# target to preprocess a source file
source/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/GameState.cpp.i
.PHONY : source/GameState.cpp.i

source/GameState.s: source/GameState.cpp.s

.PHONY : source/GameState.s

# target to generate assembly for a file
source/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/GameState.cpp.s
.PHONY : source/GameState.cpp.s

source/Logic.o: source/Logic.cpp.o

.PHONY : source/Logic.o

# target to build an object file
source/Logic.cpp.o:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/Logic.cpp.o
.PHONY : source/Logic.cpp.o

source/Logic.i: source/Logic.cpp.i

.PHONY : source/Logic.i

# target to preprocess a source file
source/Logic.cpp.i:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/Logic.cpp.i
.PHONY : source/Logic.cpp.i

source/Logic.s: source/Logic.cpp.s

.PHONY : source/Logic.s

# target to generate assembly for a file
source/Logic.cpp.s:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/Logic.cpp.s
.PHONY : source/Logic.cpp.s

source/Pattern.o: source/Pattern.cpp.o

.PHONY : source/Pattern.o

# target to build an object file
source/Pattern.cpp.o:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/Pattern.cpp.o
.PHONY : source/Pattern.cpp.o

source/Pattern.i: source/Pattern.cpp.i

.PHONY : source/Pattern.i

# target to preprocess a source file
source/Pattern.cpp.i:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/Pattern.cpp.i
.PHONY : source/Pattern.cpp.i

source/Pattern.s: source/Pattern.cpp.s

.PHONY : source/Pattern.s

# target to generate assembly for a file
source/Pattern.cpp.s:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/Pattern.cpp.s
.PHONY : source/Pattern.cpp.s

source/gl3w.o: source/gl3w.c.o

.PHONY : source/gl3w.o

# target to build an object file
source/gl3w.c.o:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/gl3w.c.o
.PHONY : source/gl3w.c.o

source/gl3w.i: source/gl3w.c.i

.PHONY : source/gl3w.i

# target to preprocess a source file
source/gl3w.c.i:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/gl3w.c.i
.PHONY : source/gl3w.c.i

source/gl3w.s: source/gl3w.c.s

.PHONY : source/gl3w.s

# target to generate assembly for a file
source/gl3w.c.s:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/gl3w.c.s
.PHONY : source/gl3w.c.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/opengl/load_image.o: source/opengl/load_image.cpp.o

.PHONY : source/opengl/load_image.o

# target to build an object file
source/opengl/load_image.cpp.o:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/opengl/load_image.cpp.o
.PHONY : source/opengl/load_image.cpp.o

source/opengl/load_image.i: source/opengl/load_image.cpp.i

.PHONY : source/opengl/load_image.i

# target to preprocess a source file
source/opengl/load_image.cpp.i:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/opengl/load_image.cpp.i
.PHONY : source/opengl/load_image.cpp.i

source/opengl/load_image.s: source/opengl/load_image.cpp.s

.PHONY : source/opengl/load_image.s

# target to generate assembly for a file
source/opengl/load_image.cpp.s:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/opengl/load_image.cpp.s
.PHONY : source/opengl/load_image.cpp.s

source/opengl/my_opengl.o: source/opengl/my_opengl.cpp.o

.PHONY : source/opengl/my_opengl.o

# target to build an object file
source/opengl/my_opengl.cpp.o:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/opengl/my_opengl.cpp.o
.PHONY : source/opengl/my_opengl.cpp.o

source/opengl/my_opengl.i: source/opengl/my_opengl.cpp.i

.PHONY : source/opengl/my_opengl.i

# target to preprocess a source file
source/opengl/my_opengl.cpp.i:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/opengl/my_opengl.cpp.i
.PHONY : source/opengl/my_opengl.cpp.i

source/opengl/my_opengl.s: source/opengl/my_opengl.cpp.s

.PHONY : source/opengl/my_opengl.s

# target to generate assembly for a file
source/opengl/my_opengl.cpp.s:
	$(MAKE) -f CMakeFiles/Supercharged-Juggernaut-Wasps.dir/build.make CMakeFiles/Supercharged-Juggernaut-Wasps.dir/source/opengl/my_opengl.cpp.s
.PHONY : source/opengl/my_opengl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Supercharged-Juggernaut-Wasps"
	@echo "... edit_cache"
	@echo "... source/Bullet.o"
	@echo "... source/Bullet.i"
	@echo "... source/Bullet.s"
	@echo "... source/Display.o"
	@echo "... source/Display.i"
	@echo "... source/Display.s"
	@echo "... source/GameState.o"
	@echo "... source/GameState.i"
	@echo "... source/GameState.s"
	@echo "... source/Logic.o"
	@echo "... source/Logic.i"
	@echo "... source/Logic.s"
	@echo "... source/Pattern.o"
	@echo "... source/Pattern.i"
	@echo "... source/Pattern.s"
	@echo "... source/gl3w.o"
	@echo "... source/gl3w.i"
	@echo "... source/gl3w.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/opengl/load_image.o"
	@echo "... source/opengl/load_image.i"
	@echo "... source/opengl/load_image.s"
	@echo "... source/opengl/my_opengl.o"
	@echo "... source/opengl/my_opengl.i"
	@echo "... source/opengl/my_opengl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

